// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buedfdrigtcxnxatdsen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1ZWRmZHJpZ3RjeG54YXRkc2VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNjM0MTUsImV4cCI6MjA2NjkzOTQxNX0.3b3Qza4QRtQ9oOg8eMlU4hkUtJgcpF7Z7Wd23JzTxY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});